version: "3.7"
services:
  reaScraperViewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: rea-scraper-viewer
    container_name: REAScraperViewer
    hostname: has.prod.rea-scraper-viewer
    restart: on-failure
